### PR TITLE
Add cropping image from zoom to safe region and split to individual

### PR DESCRIPTION
**Pull request by jisack**
Show case of cropping zoom image to safe region and individual as a fixed line X and Y also size as Readme mention that it can be hard coded.

### Safe region cropping
on file `zoom-safe-region.png`

image

### Individual images
on folder `images/`

section 1
image
section 2
image
section 3
image

.... so on

What i have done
 - Build docker image to run canvas module in server side
 - Add library `canvas`, `image-clipper`, `image-to-slices`
 - APIs added `/slice-image` for cropping image from `zoom.png` as a sample zoom image
 - Path of file `zoom-safe-region.png` as a safe region `images/*` as a individual images (49 person)

How to run 
we need docker to run because dependencies required
```
cd zoom-gallery-view-cropping && docker-compose up -d
```

### CODE REVIEW

**Comment by jisack** [comment]
Reference issues

https://github.com/SurfEdge/zoom-gallery-view-cropping/issues/6

https://github.com/SurfEdge/zoom-gallery-view-cropping/issues/5

**Comment by chamathpali** [comment]
@jisack  thanks for the PR. have you had a look at https://github.com/lovell/sharp ? and the dependencies is there any other library we can look into it?

**Comment by jisack** [comment]
@chamathpali Yes, i think sharp is same as image-clipper but image-clipper is dependencies of `image-to-slices` so i used it as image optimizer like cropping safe region. And the other dependencies is jimp but there are `image-to-slices` that is simple to separate image.

**Comment by jisack** [comment]
@chamathpali any progress ? Do i have something to concern ?

**Pull request merged**
